
export const concessionarias = [
  'Equatorial Goiás',
  'ENEL Distribuição Goiás',
  'ENEL Distribuição São Paulo',
  'ENEL Distribuição Ceará',
  'ENEL Distribuição Rio',
  'CEMIG Distribuição',
  'COPEL Distribuição',
  'CELESC Distribuição',
  'AES Eletropaulo',
  'AES Sul',
  'Light',
  'Energisa',
  'CPFL Energia',
  'RGE',
  'Coelba',
  'Cosern',
  'Coelce',
  'Celpa',
  'Cepisa',
  'Eletroacre',
  'Ceron',
  'Boa Vista Energia',
  'AmE',
  'CEB Distribuição',
  'Celg Distribuição',
  'DME Distribuição',
  'EDP São Paulo',
  'EDP Espírito Santo'
];
