// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://znsctgihxeuhjqcofgsi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpuc2N0Z2loeGV1aGpxY29mZ3NpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyMTI0NTEsImV4cCI6MjA2NTc4ODQ1MX0.WhS2sUvEtUCyIWxSEKn8BsZI3T2rp-lhplo0Jh9c-ww";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);